#!/usr/bin/env python3
"""
Waypoint Follower Node
Reads waypoints from JSON file and sends them as Nav2 goals sequentially

Features:
- Loads waypoints from JSON file generated by waypoint_recorder_node.py
- Sends waypoints to Nav2 as sequential goals
- Provides feedback on goal status
- Can be paused/resumed via service calls
- Publishes current goal and progress
"""

import rclpy
from rclpy.node import Node
from rclpy.action import ActionClient
from nav2_msgs.action import FollowWaypoints
from geometry_msgs.msg import PoseStamped
from std_msgs.msg import String, Int32, Bool
from std_srvs.srv import Trigger
import json
import os
from datetime import datetime
import math


class WaypointFollowerNode(Node):
    def __init__(self):
        super().__init__('waypoint_follower')
        
        # Declare parameters
        self.declare_parameter('waypoints_file', '')
        self.declare_parameter('goal_tolerance_linear', 0.1)
        self.declare_parameter('goal_tolerance_angular', 0.1)
        self.declare_parameter('max_linear_vel', 0.3)
        self.declare_parameter('max_angular_vel', 0.5)
        
        # Get parameters
        waypoints_file = self.get_parameter('waypoints_file').value
        self.goal_tolerance_linear = self.get_parameter('goal_tolerance_linear').value
        self.goal_tolerance_angular = self.get_parameter('goal_tolerance_angular').value
        self.max_linear_vel = self.get_parameter('max_linear_vel').value
        self.max_angular_vel = self.get_parameter('max_angular_vel').value
        
        # Expand path
        waypoints_file = os.path.expanduser(waypoints_file)
        
        # Load waypoints
        self.waypoints = []
        self.load_waypoints(waypoints_file)
        
        # State tracking
        self.current_waypoint_idx = 0
        self.is_paused = False
        self.is_running = True
        self.waypoints_completed = 0
        
        # Nav2 Action Client
        self.nav_to_pose_client = ActionClient(self, FollowWaypoints, 'follow_waypoints')
        self.nav_goal_handle = None
        
        # Publishers
        self.current_goal_pub = self.create_publisher(PoseStamped, 'waypoint_follower/current_goal', 10)
        self.progress_pub = self.create_publisher(String, 'waypoint_follower/progress', 10)
        self.waypoint_reached_pub = self.create_publisher(Int32, 'waypoint_follower/reached', 10)
        self.status_pub = self.create_publisher(String, 'waypoint_follower/status', 10)
        
        # Subscribers
        self.start_sub = self.create_subscription(
            Bool,
            'waypoint_follower/start',
            self.start_callback,
            10
        )
        
        self.pause_sub = self.create_subscription(
            Bool,
            'waypoint_follower/pause',
            self.pause_callback,
            10
        )
        
        # Services
        self.start_service = self.create_service(Trigger, 'waypoint_follower/start_mission', self.start_mission)
        self.pause_service = self.create_service(Trigger, 'waypoint_follower/pause_mission', self.pause_mission)
        self.resume_service = self.create_service(Trigger, 'waypoint_follower/resume_mission', self.resume_mission)
        self.stop_service = self.create_service(Trigger, 'waypoint_follower/stop_mission', self.stop_mission)
        
        # Timer for periodic status updates
        self.status_timer = self.create_timer(5.0, self.publish_status)
        
        self.get_logger().info('=' * 80)
        self.get_logger().info('WAYPOINT FOLLOWER NODE INITIALIZED')
        self.get_logger().info('=' * 80)
        self.get_logger().info(f'Loaded {len(self.waypoints)} waypoints')
        self.get_logger().info(f'Goal tolerance (linear): {self.goal_tolerance_linear}m')
        self.get_logger().info(f'Goal tolerance (angular): {self.goal_tolerance_angular}°')
        self.get_logger().info('')
        self.get_logger().info('AVAILABLE COMMANDS:')
        self.get_logger().info('  1. Start mission: ros2 service call /waypoint_follower/start_mission std_srvs/srv/Trigger')
        self.get_logger().info('  2. Pause mission: ros2 service call /waypoint_follower/pause_mission std_srvs/srv/Trigger')
        self.get_logger().info('  3. Resume mission: ros2 service call /waypoint_follower/resume_mission std_srvs/srv/Trigger')
        self.get_logger().info('  4. Stop mission: ros2 service call /waypoint_follower/stop_mission std_srvs/srv/Trigger')
        self.get_logger().info('=' * 80)
    
    def load_waypoints(self, waypoints_file):
        """Load waypoints from JSON file"""
        try:
            if not os.path.exists(waypoints_file):
                self.get_logger().error(f'Waypoints file not found: {waypoints_file}')
                return
            
            with open(waypoints_file, 'r') as f:
                data = json.load(f)
            
            self.waypoints = data.get('waypoints', [])
            
            self.get_logger().info(f'✅ Loaded {len(self.waypoints)} waypoints from {waypoints_file}')
            
            # Print waypoint summary
            self.get_logger().info('')
            self.get_logger().info('WAYPOINTS LOADED:')
            self.get_logger().info('─' * 80)
            for wp in self.waypoints:
                pos = wp.get('position', {})
                yaw = wp.get('yaw_degrees', 0)
                self.get_logger().info(
                    f"  [{wp['id']}] {wp['name']}: "
                    f"x={pos.get('x', 0):7.3f}m y={pos.get('y', 0):7.3f}m "
                    f"yaw={yaw:7.2f}°"
                )
            self.get_logger().info('─' * 80)
            
        except Exception as e:
            self.get_logger().error(f'Failed to load waypoints: {e}')
    
    def start_callback(self, msg):
        """Handle start trigger from subscription"""
        if msg.data:
            self.start_mission_internal()
    
    def pause_callback(self, msg):
        """Handle pause trigger from subscription"""
        self.is_paused = msg.data
        if self.is_paused:
            self.get_logger().info('Mission PAUSED')
        else:
            self.get_logger().info('Mission RESUMED')
    
    def start_mission_internal(self):
        """Internal method to start mission"""
        if len(self.waypoints) == 0:
            self.get_logger().error('No waypoints loaded!')
            return
        
        self.is_running = True
        self.is_paused = False
        self.current_waypoint_idx = 0
        self.waypoints_completed = 0
        
        self.get_logger().info('=' * 80)
        self.get_logger().info('🚀 STARTING WAYPOINT FOLLOWING MISSION')
        self.get_logger().info('=' * 80)
        
        self.send_next_goal()
    
    def start_mission(self, request, response):
        """Service callback to start mission"""
        self.start_mission_internal()
        response.success = True
        response.message = f'Starting mission with {len(self.waypoints)} waypoints'
        return response
    
    def pause_mission(self, request, response):
        """Service callback to pause mission"""
        self.is_paused = True
        if self.nav_goal_handle:
            self.nav_goal_handle.cancel_goal_async()
        
        status_msg = String()
        status_msg.data = 'mission_paused'
        self.status_pub.publish(status_msg)
        
        self.get_logger().info('Mission PAUSED')
        response.success = True
        response.message = 'Mission paused'
        return response
    
    def resume_mission(self, request, response):
        """Service callback to resume mission"""
        self.is_paused = False
        
        status_msg = String()
        status_msg.data = 'mission_resumed'
        self.status_pub.publish(status_msg)
        
        self.get_logger().info('Mission RESUMED')
        response.success = True
        response.message = 'Mission resumed'
        return response
    
    def stop_mission(self, request, response):
        """Service callback to stop mission"""
        self.is_running = False
        if self.nav_goal_handle:
            self.nav_goal_handle.cancel_goal_async()
        
        status_msg = String()
        status_msg.data = 'mission_stopped'
        self.status_pub.publish(status_msg)
        
        self.get_logger().info('=' * 80)
        self.get_logger().info('❌ MISSION STOPPED')
        self.get_logger().info(f'Completed: {self.waypoints_completed}/{len(self.waypoints)} waypoints')
        self.get_logger().info('=' * 80)
        
        response.success = True
        response.message = f'Mission stopped. Completed {self.waypoints_completed}/{len(self.waypoints)} waypoints'
        return response
    
    def send_next_goal(self):
        """Send all waypoints to Nav2 follow_waypoints action"""
        if not self.is_running:
            return
        
        if len(self.waypoints) == 0:
            self.get_logger().error('No waypoints loaded!')
            return
        
        # Create goal with all waypoints
        goal_msg = FollowWaypoints.Goal()
        goal_msg.poses = []
        
        for wp in self.waypoints:
            pose = PoseStamped()
            pose.header.frame_id = 'map'
            pose.header.stamp = self.get_clock().now().to_msg()
            
            # Set position
            pose.pose.position.x = wp['position']['x']
            pose.pose.position.y = wp['position']['y']
            pose.pose.position.z = wp['position']['z']
            
            # Set orientation (from quaternion)
            pose.pose.orientation.x = wp['orientation']['x']
            pose.pose.orientation.y = wp['orientation']['y']
            pose.pose.orientation.z = wp['orientation']['z']
            pose.pose.orientation.w = wp['orientation']['w']
            
            goal_msg.poses.append(pose)
        
        # Log
        self.get_logger().info('=' * 80)
        self.get_logger().info(f'🚀 SENDING ALL {len(self.waypoints)} WAYPOINTS TO NAV2')
        self.get_logger().info('─' * 80)
        for wp in self.waypoints:
            pos = wp['position']
            yaw = wp['yaw_degrees']
            self.get_logger().info(
                f"  [{wp['id']}] {wp['name']}: "
                f"x={pos['x']:7.3f}m y={pos['y']:7.3f}m yaw={yaw:7.2f}°"
            )
        self.get_logger().info('─' * 80)
        self.get_logger().info('Waiting for Nav2 to process waypoints...')
        self.get_logger().info('=' * 80)
        
        # Send goal to Nav2
        self.nav_to_pose_client.wait_for_server()
        self.nav_goal_handle = self.nav_to_pose_client.send_goal_async(goal_msg)
        self.nav_goal_handle.add_done_callback(self.goal_response_callback)
    
    def goal_response_callback(self, future):
        """Handle Nav2 goal response"""
        goal_handle = future.result()
        if not goal_handle.accepted:
            self.get_logger().error('❌ Nav2 rejected the goal!')
            return
        
        self.get_logger().info('✅ Nav2 accepted the goal, following waypoints...')
        
        # Get result when done
        result_future = goal_handle.get_result_async()
        result_future.add_done_callback(self.get_result_callback)
    
    def get_result_callback(self, future):
        """Handle Nav2 result"""
        try:
            result = future.result().result
            
            # Check if all waypoints were followed successfully
            if result.missed_waypoints == []:
                self.get_logger().info('=' * 80)
                self.get_logger().info('✅✅✅ ALL WAYPOINTS FOLLOWED SUCCESSFULLY ✅✅✅')
                self.get_logger().info('=' * 80)
                self.waypoints_completed = len(self.waypoints)
                self.mission_complete()
            else:
                self.get_logger().warn(f'⚠️ Missed waypoints: {result.missed_waypoints}')
                self.waypoints_completed = len(self.waypoints) - len(result.missed_waypoints)
                
        except Exception as e:
            self.get_logger().error(f'❌ Error getting result: {e}')
    
    def publish_status(self):
        """Publish periodic status update"""
        if self.waypoints_completed > 0:
            status_msg = String()
            status_msg.data = f'mission_in_progress_{self.waypoints_completed}/{len(self.waypoints)}'
            self.status_pub.publish(status_msg)
    
    def mission_complete(self):
        """Called when all waypoints are completed"""
        self.is_running = False
        
        status_msg = String()
        status_msg.data = 'mission_complete'
        self.status_pub.publish(status_msg)
        
        self.get_logger().info('=' * 80)
        self.get_logger().info('✅✅✅ MISSION COMPLETE ✅✅✅')
        self.get_logger().info('=' * 80)
        self.get_logger().info(f'All {self.waypoints_completed} waypoints reached!')
        self.get_logger().info('=' * 80)


def main(args=None):
    rclpy.init(args=args)
    
    node = None
    try:
        node = WaypointFollowerNode()
        rclpy.spin(node)
    except KeyboardInterrupt:
        if node:
            node.get_logger().info('Keyboard interrupt detected')
    except Exception as e:
        if node:
            node.get_logger().error(f'Error: {e}')
        else:
            print(f'Failed to initialize node: {e}')
    finally:
        if node:
            node.destroy_node()
        if rclpy.ok():
            rclpy.shutdown()


if __name__ == '__main__':
    main()
